config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :topics, only: [:index, :show, :new, :create] do
    resources :participants, only: [:create]
    resources :debates, only: [:create]
    resources :arguments, only: [:create, :update]
  end
  resources :debates, only: [:show, :update] do
    get '/next_phase', to: "debates#next_phase", as: :next_phase
    patch '/end_debate', to: "debates#end_debate", as: :end_debate
    patch '/set_result', to: "participants#set_result", as: :set_result
    patch '/set_communication', to: "participants#set_communication", as: :set_communication
    patch '/set_persuasiveness', to: "participants#set_persuasiveness", as: :set_persuasiveness
    patch '/set_civility', to: "participants#set_civility", as: :set_civility
    resources :uses, only: [:create, :update]
  end
  resources :users, only: [:show]
  get 'dashboard', to: 'users#dashboard', as:'dashboard'
  mount ActionCable.server => '/cable'
end

app/models/topic.rb
class Topic < ApplicationRecord
CATEGORIES = %w{Apparel Entertainment Food General Politics}
LEVELS = (1..5)
  belongs_to :user
  has_many :debates, dependent: :destroy
  has_many :arguments, dependent: :destroy
  validates :proposition, :level, :description, :category, presence: true
  validates :proposition, uniqueness: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action 
  def index
    @topics = policy_scope(Topic)
    if params[:query].present?
      sql_query = "proposition ILIKE :query OR category ILIKE :query"
      @topics = @topics.where(sql_query, query: "%#{params[:query]}%")
    else
      @topics = Topic.all.order("LOWER(proposition)")
    end
  end

  def show
    @topic = Topic.find(params[:id])
    authorize @topic
    @argument = Argument.new
  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user
    authorize @topic
    if @topic.save
      redirect_to @topic
    else
      render :new
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:proposition, :level, :description, :category, :user_id)
  end
end

app/views/topics/_topic_card.html.erb
<div class="topic-card-links">
  <%= link_to topic_path(topic) do  %>
    <div class="topic-card mb-5">
      <div class="category-icon text-center">
        <% case topic.category %>
          <% when "General" %>
            <i class="fas fa-globe-americas fa-lg"></i>
          <% when "Entertainment" %>
            <i class="fas fa-tv fa-lg"></i>
          <% when "Apparel" %>
            <i class="fas fa-tshirt fa-lg"></i>
          <% when "Politics" %>
            <i class="fas fa-landmark fa-lg"></i>
          <% else %>
             <i class="fas fa-utensils fa-lg"></i>
        <% end %>
      </div>

      <h4><%= topic.proposition %></h4>
        <div class="details-text d-flex justify-content-between">
          <p><strong><%= topic.category %> </strong></p>
          <p><strong> Complexity&nbsp</strong>
            <% case topic.level.to_i %>
            <% when 1 %>
              <i class="fas fa-chess-knight knight-blue"></i>
              <% 4.times do %>
                <i class="fas fa-chess-knight knight-grey"></i>
              <% end %>
            <% when 2 %>
                <% 2.times do %>
                  <i class="fas fa-chess-knight knight-blue"></i>
                <% end %>
                <% 3.times do %>
                  <i class="fas fa-chess-knight knight-grey"></i>
                <% end %>
            <% when 3 %>
                <% 3.times do %>
                  <i class="fas fa-chess-knight knight-blue"></i>
                <% end %>
                <% 2.times do %>
                  <i class="fas fa-chess-knight knight-grey"></i>
                <% end %>
            <% when 4 %>
                <% 4.times do %>
                  <i class="fas fa-chess-knight knight-blue"></i>
                <% end %>
                <% 1.times do %>
                  <i class="fas fa-chess-knight knight-grey"></i>
                <% end %>
            <% else %>
                <% 5.times do %>
                  <i class="fas fa-chess-knight knight-blue"></i>
                <% end %>
            <% end %>
          </p>
        </div>
    </div>
  <% end %>
</div>

app/views/topics/_topic_card_dashboard.html.erb
<div class="topic-card-links">
  <%= link_to topic_path(topic) do  %>
    <div class="dashboard-card mb-5">
      <div class="category-icon text-center">
        <% case topic.category %>
          <% when "General" %>
            <i class="fas fa-globe-americas fa-lg"></i>
          <% when "Entertainment" %>
            <i class="fas fa-tv fa-lg"></i>
          <% when "Apparel" %>
            <i class="fas fa-tshirt fa-lg"></i>
          <% when "Politics" %>
            <i class="fas fa-landmark fa-lg"></i>
          <% else %>
             <i class="fas fa-utensils fa-lg"></i>
        <% end %>
      </div>

      <h4><%= topic.proposition %></h4>
        <div class="details-text">
          <p><strong><%= topic.category %> </strong></p>
          <p><strong> Complexity&nbsp</strong>
            <% case topic.level.to_i %>
            <% when 1 %>
              <i class="fas fa-chess-knight knight-blue"></i>
              <% 4.times do %>
                <i class="fas fa-chess-knight knight-grey"></i>
              <% end %>
            <% when 2 %>
                <% 2.times do %>
                  <i class="fas fa-chess-knight knight-blue"></i>
                <% end %>
                <% 3.times do %>
                  <i class="fas fa-chess-knight knight-grey"></i>
                <% end %>
            <% when 3 %>
                <% 3.times do %>
                  <i class="fas fa-chess-knight knight-blue"></i>
                <% end %>
                <% 2.times do %>
                  <i class="fas fa-chess-knight knight-grey"></i>
                <% end %>
            <% when 4 %>
                <% 4.times do %>
                  <i class="fas fa-chess-knight knight-blue"></i>
                <% end %>
                <% 1.times do %>
                  <i class="fas fa-chess-knight knight-grey"></i>
                <% end %>
            <% else %>
                <% 5.times do %>
                  <i class="fas fa-chess-knight knight-blue"></i>
                <% end %>
            <% end %>
          </p>
        </div>
    </div>
  <% end %>
</div>

app/views/topics/_topic_sidebar.html.erb
<!--<div id="body-overlay"></div>
    <nav class="real-menu sidebar-nav" role="navigation">
        <ul>
            <li><a href="#">Item 1</a></li>
            <li><a href="#">Item 2</a></li>
            <li><a href="#">Item 3</a></li>
        </ul>
    </nav>
<button id="open-menu"><i class="fas fa-bars"></i></button> 
-->

app/views/topics/index.html.erb
<div class="topics-index container pb-5">
  <h1 class="text-center mb-5" id = "topic-index-header"> Browse Topics</h1>
  <div class="mb-5">
    <%= form_tag topics_path, method: :get, class: "search-form d-flex ml-3 mt-3" do %>
    <%= text_field_tag :query,
    params[:query],
    class: "form-control mr-2",
      placeholder: "Search a topic or category"
      %>
      <%= button_tag(type: "submit", class: "btn btn-default") do %>
      <i class="fas fa-search"></i>
      <% end %>
      <% end %>
    </div>
    <div class="topic-card-container">

      <% @topics.each do |topic| %>
      <%= render 'topic_card', topic: topic %>
      <% end %>
    </div>
</div>

app/views/topics/new.html.erb
<div class="container mt-5">
  <%= simple_form_for @topic do |f| %>
    <%= f.input :proposition %>
    <%= f.input :level, collection: Topic::LEVELS %>
    <%= f.input :description %>
    <%= f.input :category, collection: Topic::CATEGORIES %>
    <%= f.button :submit, class: "btn-new" %>
  <% end %>
</div>

app/views/topics/show.html.erb
<div class="quarter-circle-top-left">
  <%= render "shared/topic-icon" %>
  <%= link_to "", topics_path, class:"div-link" %>
</div>
<div class="container-topic-show text-center mt-3">
  <div>
    <h1 id="topic-show-title" class="mb-4"><%= @topic.proposition %></h1>
      <div class="rating-section d-flex justify-content-center align-items-center mb-3">
        <%= render "shared/rating" %>
      </div>
      <div id="topic-show-desc" class="text-left w-50 mb-3">
        <p><%= @topic.description %></p>
      </div>

      <!-- Moderator Info -->
     <!--  <div id="topic-show-desc" class="w-50 mb-5">
        <#% if @topic.user == nil? %>
          <h3>No available debate rooms</h3>
        <#% elsif @topic.user %>
        <div class="moderator-info">
          <h3 class="py-2 ">Moderator Information</h3>
          <%#= cl_image_tag @topic.user.photo, size: "70x70", class: "rounded-circle" %>
          <p class="py-2"> <%#= @topic.user.username %> </p>
        </div>

        <#% else %>
          <h3>No available debates :(</h3>
        <#% end %>
      </div>
  </div> -->

  <div class="form">
    <%= render "arguments/argument_forms" %>
    <div class="d-flex justify-content-center">
      <%#= link_to "Back to Topics", topics_path, class: "btn-new"  %>
      <% if current_user.debates.active.none? %>
      <div class="join-as-debator">
        <%= link_to "Join as Debator", topic_participants_path(@topic, debator: true), method: :post, class: "btn-new"  %>
      </div>
      <div class="join-as-moderator">
        <%= link_to "Join as Moderator", topic_participants_path(@topic, moderator: true), method: :post, class: "btn-new"  %>
      </div>
      <% else %>
        <%= link_to "You are in a debate! Go back", debate_path(current_user.debates.active.first), class: "btn-new"  %>
      <% end %>
    </div>
  </div>
</div>