config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :topics, only: [:index, :show, :new, :create] do
    resources :participants, only: [:create]
    resources :debates, only: [:create]
    resources :arguments, only: [:create, :update]
  end
  resources :debates, only: [:show, :update] do
    get '/next_phase', to: "debates#next_phase", as: :next_phase
    patch '/end_debate', to: "debates#end_debate", as: :end_debate
    patch '/set_result', to: "participants#set_result", as: :set_result
    patch '/set_communication', to: "participants#set_communication", as: :set_communication
    patch '/set_persuasiveness', to: "participants#set_persuasiveness", as: :set_persuasiveness
    patch '/set_civility', to: "participants#set_civility", as: :set_civility
    resources :uses, only: [:create, :update]
  end
  resources :users, only: [:show]
  get 'dashboard', to: 'users#dashboard', as:'dashboard'
  mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  LANGUAGE_LEVELS = ['Native', 'Advanced', 'Intermediate', 'Basic', 'Beginner']
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :photo, PhotoUploader

  has_many :arguments
  has_many :uses
  has_many :participants
  has_many :debates, through: :participants
  has_many :topics

  validates :first_name, :last_name, :username, :email, presence: true
  validates :username, :email, uniqueness: true
  validates :email, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }

  def in_debate?
    debates.active.any?
  end

  def wins
    participants.where(result: "winner").count
  end

  def losses
    participants.where(result: "loser").count
  end

  def user_rank
    games = wins + losses
    rank = ""
    if games > 0
      ratio = ((wins / games.to_f) * 100).round
    end
    if (0..19).include?(ratio)
      rank = "Bronze"
    elsif (20..39).include?(ratio)
      rank = "Silver"
    elsif (40..59).include?(ratio)
      rank = "Gold"
    elsif (60..79).include?(ratio)
      rank = "Diamond"
    elsif (80..89).include?(ratio)
      rank = "Platinum"
    elsif (90..96).include?(ratio)
      rank = "Master"
    elsif (97..100).include?(ratio)
      rank = "Grand Master"
    end
    rank
  end

  def prepared_topics
    prepared_topics = []
    arguments.each do |argument|
      prepared_topics << argument.topic
    end
    prepared_topics.uniq
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize_user
  end

  def dashboard
    @user = current_user
    @topics = Topic.first(10)
    authorize_user
  end

  private
  def authorize_user
    authorize @user
  end
end

app/views/users/_dashboard_rating.html.erb
<div class="ratings">
  <li>Communication:
    <% 4.times do %>
      <i class="fas fa-circle mr-2" style="color: #9DEDAA"></i>
    <% end %>
    <% 1.times do %>
      <i class="fas fa-circle mr-2" style="color: #CACACA"></i>
    <% end %>
  </li>
  <li>Persuasiveness:&nbsp
    <% 3.times do %>
      <i class="fas fa-circle mr-2" style="color: #9DEDAA"></i>
    <% end %>
    <% 2.times do %>
      <i class="fas fa-circle mr-2" style="color: #CACACA"></i>
    <% end %>
  </li>
  <li>Civility:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <% 5.times do %>
      <i class="fas fa-circle mr-2" style="color: #9DEDAA"></i>
    <% end %>
</li>
</div>

app/views/users/_infos.html.erb
<div class="user-sidebar">
  <div class="sidebar">
    <div class="info">
      <h4><%= current_user.username %>'s page</h4>
    </div>
    <div class="actions">
        <ul>
          <li><%= cl_image_tag @user.photo, class: "dashboard-image"%> </li>
          <li><%= @user.email %></li>
          <li> Wins: <%=  @user.wins %> </li>
          <li> Losses: <%=  @user.losses %> </li>
        </ul>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-6 p-3 ">
        <%#= link_to "Challenge", debates_path, class: "btn btn-primary" %>
        <%= link_to "Add Friend", user_path(@user), class: "btn btn-primary"  %>
      </div>
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="container-dash justify-content-between" >
  <div class="user-sidebar justify-content-around">
   <div class="actions-controller ">
    <div class="sidebar">
      <div class="username text-capitalize">
        <h3><%= current_user.username %>'s Dashboard</h3>
      </div>
      <div class="actions">
        <ul>
          <% if current_user.photo.filename %>
          <li><%= cl_image_tag current_user.photo.url(:user_photo_main), class: "dashboard-image"%> </li>
          <% else %>
          <%= image_tag "default", class: "dashboard-image" %>
          <% end %>
          <!-- <li> Wins: <i class="fas fa-trophy"></i> <%=  @user.wins %> </li>
          <li> Losses: <i class="fas fa-skull"></i> <%=  @user.losses %> </li> -->
        <hr>
        <% if  %>
          <% current_user.user_rank  == "Bronze"%>
          <h3><%= current_user.user_rank %> rank - <i class="fas fa-medal medal-bronze" style="color: #CD7F32"></i></h3>
        <% elsif  %>
          <% current_user.user_rank  == "Silver"%>
          <h3><%= current_user.user_rank %> rank - <i class="fas fa-medal medal-silver" style="color: #D5D5D5"></i></h3>
        <% elsif  %>
          <% current_user.user_rank  == "Gold"%>
          <h3><%= current_user.user_rank %> rank - <i class="fas fa-medal medal-gold" style="color: #FAD701"></i></h3>
        <% elsif  %>
          <% current_user.user_rank  == "Diamond"%>
          <h3><%= current_user.user_rank %> rank - <i class="fas fa-medal medal-diamond" style="color: #8EBEE5"></i></h3>
        <% elsif  %>
          <% current_user.user_rank  == "Platinum"%>
          <h3><%= current_user.user_rank %> rank - <i class="fas fa-medal medal-platinum" style="color: #E5E4E2"></i></h3>
        <% elsif  %>
          <% current_user.user_rank  == "Master"%>
          <h3><%= current_user.user_rank %> rank - <i class="fas fa-medal medal-master" style="color: #F7132A"></i></h3>
        <% elsif  %>
          <% current_user.user_rank  == "Grand Master"%>
          <h3><%= current_user.user_rank %> rank - <i class="fas fa-medal medal-grand-master" style="color: #7824CC"></i></h3>
        <% end %>
        <div class="d-flex justify-content-around pt-4">
          <p id="wins-text"><%= current_user.wins %> wins</p>
          <p id="losses-text"><%= current_user.losses %> losses</p>
        </div>
        <div class="pt-4">
        <%= render "users/dashboard_rating" %>
        </div>
        </ul>
      </div>
    </div>
        <div class="col-size">
          <div class="dashboard-header"><h5>Play</h5></div>
            <div class="open-debates  pt-4">
              <% @topics.each do  |topic| %>
                <%= render 'topics/topic_card_dashboard', topic: topic  %>
              <% end %>
            </div>
        </div>
        <div class="col-size">
          <div class="dashboard-header"><h5>Moderate</h5></div>
            <div class="open-debates  pt-4">
              <% @topics.reverse.each do  |topic| %>
                <%= render 'topics/topic_card_dashboard', topic: topic %>
              <% end %>
            </div>
        </div>
        <div class="col-size">
          <div class="dashboard-header"><h5>Create</h5></div>
            <div class="open-debates  pt-4">
              <div class="create-topic-card mb-5 text-center">
                <i class="fas fa-plus"></i>
                <h4>Create a new topic</h4>
                <%= link_to "", new_topic_path, class:"div-link" %>
              </div>
                <% current_user.topics.each do |topic| %>
                  <%= render 'topics/topic_card_dashboard', topic: topic %>
                <% end %>
            </div>
        </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'infos' %>