config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :topics, only: [:index, :show, :new, :create] do
    resources :participants, only: [:create]
    resources :debates, only: [:create]
    resources :arguments, only: [:create, :update]
  end
  resources :debates, only: [:show, :update] do
    get '/next_phase', to: "debates#next_phase", as: :next_phase
    patch '/end_debate', to: "debates#end_debate", as: :end_debate
    patch '/set_result', to: "participants#set_result", as: :set_result
    patch '/set_communication', to: "participants#set_communication", as: :set_communication
    patch '/set_persuasiveness', to: "participants#set_persuasiveness", as: :set_persuasiveness
    patch '/set_civility', to: "participants#set_civility", as: :set_civility
    resources :uses, only: [:create, :update]
  end
  resources :users, only: [:show]
  get 'dashboard', to: 'users#dashboard', as:'dashboard'
  mount ActionCable.server => '/cable'
end

app/views/shared/_first_dashboard.html.erb
<div class="row text-center justify-content-around p-5">

  <div class="col-sm-3 card-dash blue ">
    <%#= link_to "", debates_path, class: "card-link" %>
    <i class="fas fa-bolt card-icon"></i>
    <h1>Quick match</h1>
    <p>Ronp about a random topic with ronpers scattered around the world!</p>
  </div>

  <div class=" col-sm-3 card-dash red ">
    <%#= link_to "", debates_path, class: "card-link" %>
    <i class="far fa-eye card-icon"></i>
    <h1>Moderate</h1>
    <p>It’s your turn to judge. Watch over other ronpers and discover something new</p>
  </div>

  <div class="col-sm-3 card-dash green ">
    <%= link_to "", topics_path, class: "card-link" %>
    <i class="far fa-check-circle card-icon"></i>
    <h1>Choose</h1>
    <p>Enter the dojo. Select a topic to ronp in and prepare for the fight</p>
  </div>
</div>

<div class="row text-center justify-content-around flex-grow-1 m-5 user-info ">

  <div class="col-6 col-sm-3">
    <h3><%=  current_user.username %></h3>
    <ul>
      <li><%= cl_image_tag current_user.photo, class: "dashboard-image"%></li>
      <li class="tabs"> Email : <%= current_user.email %> </li>
      <li class="tabs"> Wins: <i class="fas fa-trophy"></i> <%=  @user.wins %> </li>
      <li class="tabs"> Losses: <i class="fas fa-skull"></i> <%=  @user.losses %> </li>
    </ul>
  </div>
  <div class="m-2">
    <h3>Your ratings</h3>
    <hr>
    <p>Communication rating</p>
    <% 4.times do %>
      <i class="fas fa-star star-yellow"></i>
    <% end %>
    <hr>
    <p>Debate rating</p>
    <% 3.times do %>
      <i class="fas fa-star star-yellow"></i>
    <% end %>
    <hr>
    <p>Civility rating</p>
    <% 5.times do %>
      <i class="fas fa-star star-yellow"></i>
    <% end %>
    <hr>
  </div>
</div>


  </div>
</div>

app/views/shared/_footer.html.erb
<!-- Footer Elements -->

<div class="footer-main my-4">
  <div  class="container d-flex align-items-end justify-content-around">



  <!-- Social buttons -->
    <ul class="list-unstyled list-inline text-center">
      <li class="list-inline-item">
        <%= link_to "https://www.linkedin.com/in/bogdanmatei90", :target => "_blank" do %>
          <i class="fab fa-linkedin"> </i>
        <% end %>
         B. Matei
      </li>
      <li class="list-inline-item">
        <%= link_to "https://www.linkedin.com/in/taisei-yamada-b16214161", :target => "_blank" do %>
          <i class="fab fa-linkedin text-danger"> </i>
        <% end %>
         T. Yamada
      </li>
      <li class="list-inline-item">
        <%= link_to "https://www.linkedin.com/in/noah-thorne-262478112/", :target => "_blank" do %>
          <i class="fab fa-linkedin text-success"> </i>
        <% end %>
         N. Thorne
      </li>
      <li class="list-inline-item">
        <%= link_to "https://www.linkedin.com/in/edward-blundell-65197a104/", :target => "_blank" do %>
          <i class="fab fa-linkedin text-warning"> </i>
        <% end %>
         E. Blundell
      </li>
    <p class="footer-copyright text-center mt-2">© Created by Ronpa Team - LeWagon Batch 310</p>
    </ul>
  </div>
</div>

  <!-- Copyright -->
<!-- Footer -->

app/views/shared/_landing_loggedin.html.erb
<div class="landing-nav navbar-expand-sm navbar-light navbar d-flex justify-content-between p-4 ">
  <div>
    <%= link_to "Sign out" , destroy_user_session_path, method: :delete, class: "btn-landing-tan"  %>
   <!--  <h1 class="ml11">
  <span class="text-wrapper">
    <span class=" line1 el"></span>
    <span class="letters">RONPA</span>
  </span>
</h1> -->
  </div>
</div>

<div class="home-header pt-4">
  <div class="container">
    <div class="row row-logo">
      <div class="col-12">
        <h1 class="ml11">
          <span class="text-wrapper">
          <span class=" line1 el"></span>
          <span class="letters big">RONPA!</span>
          </span>
        </h1>
      <!--   <h1>Enhance your language communication</h1>
        <h1>through debates</h1> -->
      </div>
    </div>
  </div>
</div>
</div>
<div class="home-content">
  <div class="container">
    <div class="row justify-content-end ml-3">
      <div class="col-6 welcome-message">
        <h2 >Welcome back, <%= current_user.first_name %>
        </h2>
        <hr>

        <div class=" mt-4">
          <%= link_to "Find a Debate", dashboard_path , class: "btn-landing-red" %>
          </div>
      </div>
    </div>
  </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>

app/views/shared/_landing_not_loggedin.html.erb
<div class="landing-nav navbar-expand-sm navbar-light navbar d-flex justify-content-between p-4 ">
  <div>
   <!--  <h1 class="ml11">
  <span class="text-wrapper">
    <span class=" line1 el"></span>
    <span class="letters">RONPA</span>
  </span>
</h1> -->
  </div>
</div>

<div class="home-header pt-4">
  <div class="container">
    <div class="row row-logo">
      <div class="col-12">
        <h1 class="ml11">
          <span class="text-wrapper">
          <span class=" line1 el"></span>
          <span class="letters big">RONPA!</span>
          </span>
        </h1>
      <!--   <h1>Enhance your language communication</h1>
        <h1>through debates</h1> -->
      </div>
    </div>
  </div>
</div>
</div>
<div class="home-content">
  <div class="container">
    <div class="row justify-content-end info-landing">
      <div class="col-8 welcome-message">
        <h2>Challenge yourself
          <hr>
          Talk about what really matters
          <hr>
          Join the world's biggest online debating community!
        </h2>
      </div>
        <div class="col-8 mt-5 buttons">
          <%= link_to "Sign up", new_user_registration_path , class: "button-land" %>
          <%= link_to "Log in", new_user_session_path, class: "button-land"  %>
        </div>
    </div>
  </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <div class="logo-nav">
    <h1 class="ml11">
          <span class="letters-logo">RONPA!</span>
        </h1>
  </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto align-items-center">
      <li class="nav-item ">
        <%= link_to "Dashboard", dashboard_path, class: "btn-nav" %>
      </li>
      <li class="nav-item">
        <%= link_to "Browse Topics", topics_path, class: "btn-nav" %>
      </li>
      <% if (params[:controller] == 'topics' && params[:action] == 'index') %>
      <li class="nav-item">
        <%= link_to "Create Topic", new_topic_path, class: "btn-nav" %>
      </li>
      <% end %>
      <li class="nav-item dropdown">
        <% if current_user.photo.filename %>
          <%= cl_image_tag current_user.photo , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag "default", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Sign out", destroy_user_session_path, class: "dropdown-item", method: :delete  %>
          <%= link_to "Edit Profile", edit_user_registration_path , class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_new_argument_form.html.erb
<%= simple_form_for [@topic, @argument] do |f| %>
  <%= f.input :content, label: 'Write your argument here!' %>
  <%= f.submit "+", class: "btn btn-primary form-inline"%>
<% end %>

app/views/shared/_rating.html.erb
<% case @topic.level.to_i %>
  <% when 1 %>
    <p class="rating-background-yellow mb-0 mr-5">Beginner</p>
    <% 1.times do %>
      <i class="fas fa-circle mr-2" style="color: #9DEDAA"></i>
    <% end %>
    <% 4.times do %>
      <i class="fas fa-circle mr-2" style="color: #CACACA"></i>
    <% end %>
  <% when 2 %>
    <p class="rating-background-yellow mb-0 mr-5">Beginner</p>
    <% 2.times do %>
      <i class="fas fa-circle mr-2" style="color: #9DEDAA"></i>
    <% end %>
    <% 3.times do %>
      <i class="fas fa-circle mr-2" style="color: #CACACA"></i>
    <% end %>
  <% when 3 %>
    <p class="rating-background-orange mb-0 mr-5">Intermediate</p> 
    <% 3.times do %>
      <i class="fas fa-circle mr-2" style="color: #9DEDAA"></i>
    <% end %>
    <% 2.times do %>
      <i class="fas fa-circle mr-2" style="color: #CACACA"></i>
    <% end %>
  <% when 4 %>
    <p class="rating-background-orange mb-0 mr-5">Intermediate</p> 
    <% 4.times do %>
      <i class="fas fa-circle mr-2" style="color: #9DEDAA"></i>
    <% end %>
    <% 1.times do %>
      <i class="fas fa-circle mr-2" style="color: #CACACA"></i>
    <% end %>
  <% when 5 %>
    <p class="rating-background-red mb-0 mr-5">Professional</p> 
    <% 5.times do %>
      <i class="fas fa-circle mr-2" style="color: #9DEDAA"></i>
    <% end %>
<% end %>

app/views/shared/_timer.html.erb
<p class="values text-center" id="value">--:--</p>

app/views/shared/_topic-icon.html.erb
<% case @topic.category %>
  <% when "General" %>
    <i class="fas fa-globe-americas topic-show-icon fa-3x"></i>
  <% when "Entertainment" %>
    <i class="fas fa-tv topic-show-icon fa-3x"></i>
  <% when "Apparel" %>
    <i class="fas fa-tshirt topic-show-icon fa-3x"></i>
  <% when "Politics" %>
    <i class="fas fa-landmark topic-show-icon fa-3x"></i>
  <% else %>
    <i class="fas fa-utensils topic-show-icon fa-3x"></i>
<% end %>

app/views/shared/_video_chat.html.erb
<body>
  <video id="video" autoplay></video>
</body>

<script src="https://unpkg.com/peerjs@1.0.0/dist/peerjs.min.js">
 navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;

  var myStream;
  $(function(){
    navigator.getUserMedia({audio: true, video: true}, function(stream){
      myStream = stream;
      $('#video').prop('src', URL.createObjectURL(stream));
    }, function(){});
  });
</script>