config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :topics, only: [:index, :show, :new, :create] do
    resources :participants, only: [:create]
    resources :debates, only: [:create]
    resources :arguments, only: [:create, :update]
  end
  resources :debates, only: [:show, :update] do
    get '/next_phase', to: "debates#next_phase", as: :next_phase
    patch '/end_debate', to: "debates#end_debate", as: :end_debate
    patch '/set_result', to: "participants#set_result", as: :set_result
    patch '/set_communication', to: "participants#set_communication", as: :set_communication
    patch '/set_persuasiveness', to: "participants#set_persuasiveness", as: :set_persuasiveness
    patch '/set_civility', to: "participants#set_civility", as: :set_civility
    resources :uses, only: [:create, :update]
  end
  resources :users, only: [:show]
  get 'dashboard', to: 'users#dashboard', as:'dashboard'
  mount ActionCable.server => '/cable'
end

app/models/debate.rb
class Debate < ApplicationRecord
  belongs_to :topic
  has_many :uses, dependent: :destroy
  has_many :participants, dependent: :destroy

  enum phase: {
    waiting_start: 0,
    count_in: 1,
    affirmative_speech: 2,
    negative_speech: 3,
    affirmative_cross_examination: 4,
    negative_cross_examination: 5,
    affirmative_closing_statement: 6,
    negative_closing_statement: 7,
    waiting_end: 8,
    finished: 9
  } do
  end

  PHASE_TITLES = {
    waiting_start: "Finding participants...",
    count_in: "Count-down",
    affirmative_speech: "Affirmative opening arguments",
    # negative_cross_examination_preparation: "Negative questioning prep",
    # negative_cross_examination: "Negative questioning",
    # negative_speech_preparation: "Negative opening argument prep",
    negative_speech: "Negative opening arguments",
    affirmative_cross_examination: "Affirmative questioning",
    negative_cross_examination: "Negative questioning",
    # affirmative_cross_examination_preparation: "Affirmative questioning prep",
    # affirmative_cross_examination: "Affirmative questioning",
    # affirmative_closing_statement_preparation: "Affirmative closing prep",
    affirmative_closing_statement: "Affirmative closing",
    # negative_closing_statement_preparation: "Negative closing prep",
    negative_closing_statement: "Negative closing",
    waiting_end: "Final scoring",
    finished: "<h3>The winner is Someone</h3>"
  }

  AFFIRMATIVE_PHASES = [
    :affirmative_speech,
    # :affirmative_cross_examination_preparation,
    :affirmative_cross_examination,
    # :affirmative_closing_statement_preparation,
    :affirmative_closing_statement
  ]

  NEGATIVE_PHASES = [
    # :negative_speech_preparation,
    :negative_speech,
    # :negative_cross_examination_preparation,
    :negative_cross_examination,
    # :negative_closing_statement_preparation,
    :negative_closing_statement
  ]

  MODERATOR_PHASES = [
    :waiting_start,
    :count_in,
    :waiting_end
  ]

  scope :active, -> { where.not(phase: :finished) }

  def affirmative_turn?
    AFFIRMATIVE_PHASES.include?(phase.to_sym)
  end

  def negative_turn?
    NEGATIVE_PHASES.include?(phase.to_sym)
  end

  def moderator_turn?
    MODERATOR_PHASES.include?(phase.to_sym)
  end

  def phase_type
    if affirmative_turn?
      return "affirmative"
    elsif negative_turn?
      return "negative"
    else
      return "neutral"
    end
  end

  def self.phase_type(phase)
    if AFFIRMATIVE_PHASES.include?(phase)
      return "affirmative"
    elsif NEGATIVE_PHASES.include?(phase)
      return "negative"
    else
      return "neutral"
    end
  end

  def moderator_user
    participants.moderator.first&.user
  end

  def affirmative_user
    participants.affirmative.first&.user
  end

  def negative_user
    participants.negative.first&.user
  end

  def broadcast_advance(user)
    ActionCable.server.broadcast("debate_#{id}", {
      current_phase: phase,
      current_user_id: user.id
    })
  end

  def with_slot?(role)
    participants.send(role).none?
  end

end

app/controllers/debates_controller.rb
class DebatesController < ApplicationController
  def show
    @debate = Debate.includes(:participants).find(params[:id])
    @participants = @debate.participants
    @my_participant = @participants.find { |p| p.user == current_user }
    authorize @debate
    if @debate.finished?
      render 'debates/results'
    else
      render 'debates/show'
    end
  end

  def create
    @topic = Topic.find(params[:topic_id])
    authorize @topic
    if current_user.arguments.where(topic_id: @topic.id).count >= 6 && !current_user.in_debate?
      @debate = Debate.new(topic: @topic)
      @debate.phase = 0
      authorize @debate
      if @debate.save
        Participant.create(debate: @debate, role: "moderator", user: current_user)
        redirect_to debate_path(@debate)
      end
    else
      redirect_to topic_path(@topic)
    end
  end

  def next_phase
    @debate = Debate.find(params[:debate_id])
    @topic = @debate.topic
    authorize @debate
    if Debate.phases[@debate.phase.to_sym] < Debate.phases.count - 1
      @debate.update(phase: Debate.phases[@debate.phase] + 1)
      DebatesChannel.broadcast_debate_data(@debate)
      respond_to do |format|
        format.html { render 'debates/show' }
        format.js
      end
    else
      redirect_to debate_path(@debate)
    end
  end

  def end_debate
    @debate = Debate.find(params[:debate_id])
    @topic = @debate.topic
    authorize @debate
    @debate.update(phase: 9)
    redirect_to dashboard_path
  end

  private

  def debate_params
    params.require(:debate).permit(:debate_id)
  end
end

app/views/debates/_affirmative_view.html.erb
<div class="d-flex debate-show">
  <div class="timeline-sidebar">
    <%= render "debates/timeline", debate: debate %>
  </div>

  <div class="container pl-0 pr-0">
    <div id="debate-box">
      <h1 class="text-center topic-proposition-text"><%= debate.topic.proposition%></h1>
      <div class="d-flex justify-content-around">
        <h3 class="role text-center ml-5">Affirmative Position</h3>
        <h4><%= link_to "Join Call", "https://whereby.com/ronpa", target: :_blank, class: "blue-hvr-outline-in"  %></h4>
        <h3 class="role text-center mr-5">Negative Position</h3>
      </div>
      <div class="row justify-content-center">
        <div class="phase">
          <h3 class='phase-text'>
            <%= render "debates/debate_phase", debate: debate %>
          </h3>
          <%= render 'shared/timer' %>
        </div>
      </div>

      <!-- USER INFO -->
      <div class="d-flex justify-content-around pb-4">
        <div id="affirmative-user-info">
          <% if debate.affirmative_user %>
            <%= render 'debates/user_info', user: debate.affirmative_user %>
          <% end %>
        </div>
        <div id="negative-user-info">
          <% if debate.negative_user %>
            <%= render 'debates/user_info', user: debate.negative_user %>
          <% end %>
        </div>
      </div>

      <!-- USER PANES -->
      <div class="d-flex justify-content-around">
        <div>
          <div class="user-pane-affirmative">
            <% if debate.affirmative_user %>
              <%= render 'debates/user_pane_affirmative', user: debate.affirmative_user, debate: debate %>
            <% end %>
          </div>
          <div class="button-container">
            <div class="button-affirmative">
              <% if debate.affirmative_turn? %>
                <div class="text-center mt-4">
                  <div class="end-turn-button">
                    <h4><%= link_to "End Turn", debate_next_phase_path(debate), method: :patch, remote: true, class: "hvr-outline-in"  %></h4>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div>
          <div class="user-pane-negative">
            <% if debate.negative_user %>
              <%= render 'debates/user_pane_negative', user: debate.negative_user, debate: debate %>
            <% end %>
          </div>
          <div class="button-container">
            <div class="button-negative">
              <% if debate.negative_turn? %>
                <div class="text-center mt-4">
                  <div class="end-turn-button">
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <!-- MOD STUFF -->
      <div>
        <div class="text-center text-moderator">
            <% if debate.moderator_user %>
            <div class="moderator-icon d-flex">
              <div class="mr-2">
                <%= cl_image_tag debate.participants.moderator.first.user.photo, class:"text-center moderator-image" %>
                <h4><%= debate.moderator_user.username %> is Moderator</h>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/debates/_debate_phase.html.erb
<h3>
  <% case debate.phase %>
  <% when "waiting_start"%>
    Waiting for match to start...
  <% when "count_in"%>
    Affirmative opening arguments will start in:
  <% when "affirmative_speech"%>
    Affirmative opening arguments
  <% when "negative_cross_examination_preparation"%>
    Negative cross examination preparation
  <% when "negative_cross_examination"%>
    Negative cross examination
  <% when "negative_speech_preparation"%>
    Negative opening argument preparation
  <% when "negative_speech"%>
    Negative opening arguments
  <% when "affirmative_cross_examination_preparation"%>
    Affirmative cross examination preparation
  <% when "affirmative_cross_examination"%>
    Affirmative cross examination
  <% when "affirmative_closing_statement_preparation"%>
    Affirmative closing statement prepatation
  <% when "affirmative_closing_statement"%>
    Affirmative closing statements
  <% when "negative_closing_statement_preparation"%>
    Negative closing statement preparation
  <% when "negative_closing_statement"%>
    Negative closing statements
  <% when "waiting_end"%>
    Moderator giving final score...
  <% end %>
</h3>

app/views/debates/_feedback_icons_winner.html.erb
<div class="feedback-icons row justify-content-around">
  <div>
    <a href="#">
      <div class="feedback-icon-tan ml-4">
        <i class="far fa-thumbs-up"></i>
      </div>
    </a>
    <p class="text-center">Good Communication</p>
  </div>
  <div>
    <a href="#">
      <div class="feedback-icon-tan">
        <i class="far fa-smile"></i>
      </div>
    </a>
    <p class="text-center">Persuasive</p>
  </div>
  <div>
    <a href="#">
      <div class="feedback-icon-tan">
        <i class="fas fa-crown"></i>
      </div>
    </a>
    <p class="text-center">Civil</p>
  </div>
</div>

app/views/debates/_loser_results.html.erb
<div class="container" id="results-box-loser">
  <div class="mb-5">
    <h1>Defeat</h1>
    <h3 class="mb-3">Good effort, keep on Ronping!</h3>
    <p>Add some feedback for your opponent below and help keep Ronpa a great place to debate.</p>
  </div>
  <%= render 'feedback_icons_loser' %>
  <div id="results-buttons">
    <div class="d-flex justify-content-start">
      <%= link_to dashboard_path, class: "btn-light-red" do %>
        <i class="fas fa-exclamation-triangle"></i> Report a Participant
      <% end %>
    </div>
    <div class="d-flex justify-content-end">
      <%= link_to "Dashboard", dashboard_path, class: "btn-light-red mx-3" %>
      <%= link_to "Debate Topic Again", topic_path(@debate.topic), class: "btn-light-red" %>
    </div>
  </div>
</div>

app/views/debates/_moderator_view.html.erb
<div class="d-flex debate-show">
  <div class="timeline-sidebar">
    <%= render "debates/timeline", debate: debate %>
  </div>

  <div class="container pl-0 pr-0">
    <div id="debate-box">
      <h1 class="text-center topic-proposition-text"><%= debate.topic.proposition%></h1>
      <div class="d-flex justify-content-around">
        <h3 class="role text-center ml-5">Affirmative Position</h3>
        <h4><%= link_to "Join Call", "https://whereby.com/ronpa", target: :_blank, class: "blue-hvr-outline-in"  %></h4>
        <h3 class="role text-center mr-5">Negative Position</h3>
      </div>
      <div class="row justify-content-center">
        <div class="phase">
          <h3 class='phase-text'>
            <%= render "debates/debate_phase", debate: debate %>
          </h3>
          <%= render 'shared/timer' %>
        </div>
      </div>

      <!-- USER INFO -->
      <div class="d-flex justify-content-around pb-4">
        <div id="affirmative-user-info">
          <% if debate.affirmative_user %>
            <%= render 'debates/user_info', user: debate.affirmative_user %>
          <% end %>
        </div>
        <div id="negative-user-info">
          <% if debate.negative_user %>
            <%= render 'debates/user_info', user: debate.negative_user %>
          <% end %>
        </div>
      </div>

      <!-- USER PANES -->
      <div class="d-flex justify-content-around">
        <div>
          <div class="user-pane-affirmative">
            <% if debate.affirmative_user %>
              <%= render 'debates/user_pane_affirmative', user: debate.affirmative_user, debate: debate %>
            <% end %>
          </div>
          <div class="button-container">
            <div class="button-affirmative">
              <% if debate.affirmative_turn? %>
                <div class="text-center mt-4">
                  <div class="end-turn-button">
                  
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div>
          <div class="user-pane-negative">
            <% if debate.negative_user %>
              <%= render 'debates/user_pane_negative', user: debate.negative_user, debate: debate %>
            <% end %>
          </div>
          <div class="button-container">
            <div class="button-negative">
              <% if debate.negative_turn? %>
                <div class="text-center mt-4">
                  <div class="end-turn-button">
                    
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <!-- MOD STUFF -->
      <div>
        <div class="text-center text-moderator">
            <% if debate.moderator_user %>
            <div class="moderator-icon d-flex">
              <div class="mr-2">
                <%= cl_image_tag debate.participants.moderator.first.user.photo, class:"text-center moderator-image" %>
                <h4><%= debate.moderator_user.username %> is Moderator</h>
              </div>
            <% end %>
          </div>
          <% if debate.moderator_user %>
            <div class="button-container" id="moderator-buttons">
              <% if debate.affirmative_user && debate.waiting_end? %>
                <%= link_to "Affirmative Wins", debate_set_result_path(debate, winner_id: debate.participants.affirmative.first), method: :patch, class: "hvr-outline-in", id: "affirmative-win-button"  %>
              <% end %>
              <% if true %>
                <h4><%= link_to "End Turn", debate_next_phase_path(debate), method: :patch, remote: true, class: "hvr-outline-in" %></h4>
              <% end %>
              <% if debate.negative_user && debate.waiting_end? %>
                <%= link_to "Negative Wins", debate_set_result_path(debate, winner_id: debate.participants.negative.first), method: :patch, class: "hvr-outline-in", id: "negative-win-button" %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/debates/_progress_button.html.erb
 <%= link_to "Progress Phase", debate_next_phase_path(@debate), class: "btn-new next-phase",
              method: :patch %>

app/views/debates/_updated_show.html.erb
<div class="d-flex debate-show justify-content-between">
  <div class="timeline-sidebar ml-4">
    <%= render "debates/timeline", debate: debate %>
  </div>

  <div class="flex-grow-1 mr-4">
    <div id="debate-box" class="ml-5">
      <h1 class="text-center topic-proposition-text mb-3"><%= debate.topic.proposition%></h1>

     <div class="row justify-content-center align-items-center ml-2 mr-2">

       <div class="d-flex justify-content-around mt-3 col-4">
          <div id="affirmative-user-info">
            <% if debate.moderator_user %>
            <div class="user-icon d-flex moderator-call">
              <div class="mr-2">
                <%= cl_image_tag debate.participants.moderator.first.user.photo, class:"moderator-image" %>
              </div>
              <div>
                <h4 class='moderator-username'><%= debate.moderator_user.username %></h4>
              </div>
            </div>
            <p class="role text-right ml-5">Moderator</p>
            <% end %>
          </div>
        </div>
       <div class="phase text-center col-4">
        <h3 class='phase-text'>
          <%= render "debates/debate_phase", debate: debate %>
        </h3>
        <%= render 'shared/timer' %>
      </div>
      <div class="text-center col-4">
        <h4><%= link_to "Join Call", "https://whereby.com/ronpa", target: :_blank, class: "blue-hvr-outline-in", id: "join-call"  %></h4>
      </div>
    </div>

    <!-- USER INFO -->
    <div class="d-flex justify-content-around pb-1 mt-5">
      <div id="affirmative-user-info">
        <% if debate.affirmative_user %>
        <%= render 'debates/user_info', user: debate.affirmative_user %>
        <p class="role text-center ml-5">Affirmative Position</p>
        <% end %>
      </div>
      <div id="negative-user-info">
        <% if debate.negative_user %>
        <%= render 'debates/user_info', user: debate.negative_user %>
        <p class="role text-right ml-5 pr-0">Negative Position</p>
        <% end %>
      </div>
    </div>

    <!-- USER PANES -->
    <div class="d-flex justify-content-around">
      <div>
        <div class="user-pane-affirmative">
          <% if debate.affirmative_user && debate.affirmative_turn? %>
          <%= render 'debates/user_pane_affirmative_active', user: debate.affirmative_user, debate: debate %>
          <% elsif debate.affirmative_user  %>
          <%= render 'debates/user_pane_affirmative_inactive', user: debate.affirmative_user, debate: debate %>
          <% end %>
        </div>
        <div class="button-container">
          <div class="button-negative text-center mt-3">
            <% if debate.affirmative_user && debate.affirmative_turn? %>
            <h4><%#= link_to "End Turn", debate_next_phase_path(debate), method: :patch, remote: true, class: "hvr-outline-in"  %></h4>
            <% end %>
          </div>
        </div>
      </div>
      <div>
        <div class="user-pane-negative">
          <% if debate.negative_user && debate.negative_turn? %>
          <%= render 'debates/user_pane_negative_active', user: debate.negative_user, debate: debate %>
          <% elsif debate.negative_user  %>
          <%= render 'debates/user_pane_negative_inactive', user: debate.negative_user, debate: debate %>
          <% end %>
        </div>
        <div class="button-container">
          <div class="button-negative text-center mt-3">
            <% if debate.negative_user && debate.negative_turn? %>
            <h4><%#= link_to "End Turn", debate_next_phase_path(debate), method: :patch, remote: true, class: "hvr-outline-in"  %></h4>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="button-container text-center">
      <h4>

        <!-- MOD STUFF -->
        <% if debate.waiting_end? %>
        <div>
          <div id="set-results-controls" class="hidden text-center text-moderator">
            <div class="button-container" id="moderator-buttons">
              <%= link_to "Affirmative Wins", debate_set_result_path(debate, winner_id: debate.participants.affirmative.first), method: :patch, class: "hvr-outline-in", id: "affirmative-win-button"  %>
              <%= link_to "Negative Wins", debate_set_result_path(debate, winner_id: debate.participants.negative.first), method: :patch, class: "hvr-outline-in", id: "negative-win-button" %>
            </div>
          </div>
        </div>
        <% end %>
        <form id="end-turn-form" action="/debates/<%= debate.id %>/next_phase" class="<%= 'hidden' if debate.phase == 'waiting_end' %>">
          <button id="end-turn-btn" class="hvr-outline-in" type="submit" value="End Turn" disabled="disabled">End Turn</button>
        </form>
      </h4>
    </div>
  </div>
</div>
</div>
</div>



<div class="col-4">
  <div class="text-center">
   <h4><%= link_to "Quit Match", debate_end_debate_path(debate), method: :patch, class: "blue-hvr-outline-in"  %></h4>
 </div>
</div>

app/views/debates/_user_pane_affirmative.html.erb
<div id="argument-uses-left">
  <% if user %>
      <% user.arguments.affirmative.where(topic: debate.topic).each_with_index do |argument, index| %>
      <div class="flip-card">
<!--         <div class="card__face card__face--front">Argument <%#= index + 1 %></div> -->
        <div class="argument-use-affirmative"><%= argument.content %> </div>
      </div>
      <% end %>
  <% end %>
</div>


<!-- card__face card__face--back  -->

app/views/debates/_user_pane_affirmative_active.html.erb
<div id="argument-uses-left-active">
  <% if user %>
      <% user.arguments.affirmative.where(topic: debate.topic).each_with_index do |argument, index| %>
      <div class="flip-card">
<!--         <div class="card__face card__face--front">Argument <%#= index + 1 %></div> -->
        <div class="argument-use-affirmative"><%= argument.content %> </div>
      </div>
      <% end %>
  <% end %>
</div>

app/views/debates/_user_pane_affirmative_inactive.html.erb
<div id="argument-uses-left-inactive">
  <% if user %>
      <% user.arguments.affirmative.where(topic: debate.topic).each_with_index do |argument, index| %>
      <div class="flip-card">
<!--         <div class="card__face card__face--front">Argument <%#= index + 1 %></div> -->
        <div class="argument-use-affirmative"><%= argument.content %> </div>
      </div>
      <% end %>
  <% end %>
</div>


<!-- card__face card__face--back  -->

app/views/debates/_user_pane_negative.html.erb
<div id="argument-uses-right">
  <% if user %>
    <% user.arguments.negative.where(topic: debate.topic).each_with_index do |argument, index| %>
        <div class="flip-card">
<!--           <div class="card__face card__face--front">Argument <%#= index + 1 %></div> -->
          <div class="argument-use-negative"><%= argument.content %> </div>
        </div>
    <% end %>
  <% end %>
</div>

<!-- card__face card__face--back  -->

app/views/debates/_user_pane_negative_inactive.html.erb
<div id="argument-uses-right-inactive">
  <% if user %>
    <% user.arguments.negative.where(topic: debate.topic).each_with_index do |argument, index| %>
        <div class="flip-card">
<!--           <div class="card__face card__face--front">Argument <%#= index + 1 %></div> -->
          <div class="argument-use-negative"><%= argument.content %> </div>
        </div>
    <% end %>
  <% end %>
</div>

<!-- card__face card__face--back  -->

app/views/debates/_waiting_for_participant.html.erb
<div class="wait d-flex">
  <div class="wait">
    <h4>Looking for participant...</h4>
  </div>
</div>

app/views/debates/results.html.erb
<%= render 'shared/navbar' %>

<%= render 'results', debate: @debate %>